context:
  version: "5.63.0"

package:
  name: knip
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/knip/-/knip-${{ version }}.tgz
  sha256: a7c598853437e131a60450caa06b6bcd1267251cb1bfa26baf3ad5663baa8915

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - knip --help

about:
  license: ISC
  license_file:
    - license
    - third-party-licenses.txt
  summary: OFind unused files, dependencies and exports in your JavaScript and TypeScript projects.
  homepage: https://github.com/webpro-nl/knip
  repository: https://github.com/webpro-nl/knip

extra:
  recipe-maintainers:
    - danielnachun
