context:
  version: "5.60.1"

package:
  name: knip
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/knip/-/knip-${{ version }}.tgz
  sha256: 4f35dd74efcb4b17dfd4e1a99f765c0762d3dbd88481c89fba0a05b329057137

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - knip --help

about:
  license: ISC
  license_file:
    - license
    - third-party-licenses.txt
  summary: OFind unused files, dependencies and exports in your JavaScript and TypeScript projects.
  homepage: https://github.com/webpro-nl/knip
  repository: https://github.com/webpro-nl/knip

extra:
  recipe-maintainers:
    - danielnachun
