context:
  version: "5.46.0"

package:
  name: knip
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/knip/-/knip-${{ version }}.tgz
  sha256: 465944747884f543adfa3bd79484baea2a923d90db53a6f51d7197780182522a

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - knip --help

about:
  license: ISC
  license_file:
    - license
    - third-party-licenses.txt
  summary: OFind unused files, dependencies and exports in your JavaScript and TypeScript projects.
  homepage: https://github.com/webpro-nl/knip
  repository: https://github.com/webpro-nl/knip

extra:
  recipe-maintainers:
    - danielnachun
