context:
  version: "5.58.0"

package:
  name: knip
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/knip/-/knip-${{ version }}.tgz
  sha256: c42f03696d9f2c8b59ebd98b5abb99f72f3f20696b32f34d47e1a64dbaf76096

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - knip --help

about:
  license: ISC
  license_file:
    - license
    - third-party-licenses.txt
  summary: OFind unused files, dependencies and exports in your JavaScript and TypeScript projects.
  homepage: https://github.com/webpro-nl/knip
  repository: https://github.com/webpro-nl/knip

extra:
  recipe-maintainers:
    - danielnachun
