context:
  version: "5.51.1"

package:
  name: knip
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/knip/-/knip-${{ version }}.tgz
  sha256: d5aefec9e93aa19555e80df84de6a041a681241209d4e47e2e5fb9a274ff83b8

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - knip --help

about:
  license: ISC
  license_file:
    - license
    - third-party-licenses.txt
  summary: OFind unused files, dependencies and exports in your JavaScript and TypeScript projects.
  homepage: https://github.com/webpro-nl/knip
  repository: https://github.com/webpro-nl/knip

extra:
  recipe-maintainers:
    - danielnachun
